### ISSUE TITLE
Missing placeholder in error messages

### ISSUE THREAD

**Issue by martinvw** [openhab/org.openhab.binding.zwave#1014]
Hello @cdjackson, 

I see that you use translations for some labels:

https://github.com/openhab/org.openhab.binding.zwave/blob/77017ebbb753d1e8a9bbf5d1b9eb4bb287cfc0d0/ESH-INF/i18n/thingstate.properties

However those {0} are not being filled, so I get the error:

Status: OFFLINE - COMMUNICATION_ERROR Serial Error: Port {0} does not exist

**Comment by lolodomo** [comment]
I will provide a fix.

**Comment by lolodomo** [comment]
Could now be closed.
