### ISSUE TITLE
Transaction: Wakeup class isn't respected

### ISSUE THREAD

**Issue by cdjackson** [openhab/org.openhab.binding.zwave#102]
messages can be sent to battery devices when they aren't awake.

#64

**Comment by cdjackson** [comment]
This should now be solved although I've currently only tested it with unit tests not real life ;)

**Comment by mhilbush** [comment]
Great. I'll test it but I may not be able to get to it until Monday.

**Comment by cdjackson** [comment]
No worries - I’m still trying to work out how to manage the queue!

Thanks

**Comment by mhilbush** [comment]
This looks good to me.  I can see the messages being queued, then transmitted when the device wakes up.  Ok to close from my perspective.

**Comment by cdjackson** [comment]
Thanks great - thanks.
