### ISSUE TITLE
Support of COMMAND_CLASS_PROTECTION

### ISSUE THREAD

**Issue by thefathefa** [openhab/org.openhab.binding.zwave#1026]
Hello Chris,

As discussed in the forums, I'm interested in the ability to use COMMAND_CLASS_PROTECTION with the Zwave binding...

The user manual for the Poop valves I use says the following:
![screenshot_20181009-005605](https://user-images.githubusercontent.com/32397407/46623022-ea1e0380-cb5e-11e8-9df1-6df8d73ec0ba.jpg)
Thanks in advance,

**Comment by cdjackson** [comment]
Closed by #1182, #1183, #1242

**Comment by thefathefa** [comment]
Hello @cdjackson ,

I see that you have tagged this "closed", I looked at the other tickets you refer to but I'm not sure I understand how I can get access to this capability?

Thanks,
