### ISSUE TITLE
Fibaro multisensor FGMS-001 does not work on latest zwave snapshot 

### ISSUE THREAD

**Issue by s2wallace** [openhab/org.openhab.binding.zwave#1029]
I have upgraded to the latest milestone build (2.4 M4) on my raspberrypi loaded with raspbian. Previous to this my 2 x Fibaro FGMS-001 were working correctly. Now I get nothing back from either of them.

I have followed the instructions for the new zwave binding by removing all zwave components and re-adding them back. Some of my z-wave devices do work but the 2 x FGMS-001 do not work at all. I have tried waking them up,leaving for several days etc but no luck

No XML files are being created for these!

[zwave.log](https://github.com/openhab/org.openhab.binding.zwave/files/2466525/zwave.log)

**Comment by cdjackson** [comment]
I would suggest to discuss on the forum, but the first thing to do is to wake up the devices so they can initialise.
