### ISSUE TITLE
strike lock configuration and usage issue

### ISSUE THREAD

**Issue by wrosenauer** [openhab/org.openhab.binding.zwave#1049]
* OH2 Version: 2.4.0-SNAPSHOT Build #1401
* Binding Version (if SNAPSHOT, provide compile time as found on the filename in the console): as included in above build 2.4.0~20181026171748-1

If the problem is associated with a device, please provide the following -:

* Device name: 012501 Electric Strike Lock Control
* Device version: 1.5
* Link to [database]: https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/419
* If there is an XML being generted for the device (in the /userdata/zwave folder), please provide it.
Cannot find any /userdata/zwave folder on my openhabian installation

Provide a full debug level log of the problem. Preferably, you should try use the [log viewer](http://www.cd-jackson.com/index.php/openhab/zwave-log-viewer) to see if you can identify the problem.
Logs are attached. I'm not familiar with z-wave so even using the zwave-log-viewer I cannot spot an issue.

I tried to describe my issue a few days ago here:
https://community.openhab.org/t/configuration-for-a-door-lock-control-relay-based/55002

Since there was no feedback and I meanwhile collected debug logs of the zwave binding I'm filing this here as well.
Short problem description (with reference to the logs):
The first part of the log is from trying to change the lock timeout from the default 3 seconds to 2 seconds. There is no error shown in HABmin but the change does not stick. It stays on 3 seconds always.
The second part of the log is when I set the lock to "UNLOCKED" and waiting for the timeout of 3 seconds. But this timeout does not happen. The relay stays on permanently until I switch to "LOCKED" manually. While I'm sure I can create a rule or a scene to overcome that I would be interested what is going wrong here.
[openhab.log](https://github.com/openhab/org.openhab.binding.zwave/files/2538159/openhab.log)

**Comment by cdjackson** [comment]
Please post questions on the forum. I'd suggest to update your forum post with your new information rather than cross posting here. Feel free to mention me with @chris and I'll try and answer.

**Comment by wrosenauer** [comment]
Sorry to bother here, but it's now almost two months without any progress on my "question" in the forum. Either it is a bug and the report here would be the right way or I don't know.
