### ISSUE TITLE
Update some channels categories

### ISSUE THREAD

**Issue by bodiroga** [openhab/org.openhab.binding.zwave#1068]
Hi @cdjackson!

Having a look at the channels.xml file, I have spotted that some channel-types don't have their categories correctly set or the field is empty. Here you have my suggestions:

- alarm_battery -> LowBattery (empty)
- alarm_co2 -> CarbonDioxide (Door)
- alarm_emergency -> Alarm (empty)
- alarm_flood -> Water (Door)
- alarm_general -> Alarm (Door)
- alarm_heat -> Fire (empty)
- alarm_motion -> Motion (Door)
- alarm_power -> Energy (Door)
- color_color -> ColorLight (empty)
- meter_water_cubic_meters -> Water (Energy)
- meter_water_cubic_feet -> Water (Energy)
- meter_water_gallons -> Water (Energy)
- meter_water_pulse -> Water (Energy)
- sensor_barpressure -> Pressure (empty)
- sensor_binary -> empty (Door)
- sensor_co2 -> CarbonDioxide (empty)
- sensor_flood -> Water (empty)
- sensor_seismicintensity -> empty (Humidity)
- sensor_ultraviolet -> empty (Temperature)
- thermostat_setpoint -> Heating (Temperature)

Are those values encoded in the database or can I make a PR to change them? Will you consider reviewing a PR with the proposed changes? I will be happy to submit one :wink: 

Many thanks for your time and best regards,

Aitor

**Comment by cdjackson** [comment]
They aren't encoded in the database - the database actually reads the XML file to generate the documentation, so updating the XML will be fine, and a PR would be great (thanks).
