### ISSUE TITLE
Enerwave ZWN-RSM2 can't change configuration parameter

### ISSUE THREAD

**Issue by luiscampiz** [openhab/org.openhab.binding.zwave#1088]
Can't change configuration parameter number 3 (Unsolicited Report Configuration)
Attached log, xml file from device with issue (NODE 16) , and another one from an older device that is working ok (NODE 4).
The log start when I reinitialize the device and end after I try to change the parameter.
The Attachment is a ZIP file.

* OH2 Version: 2.4.0-SNAPSHOT Build #1460   
* Binding Version:  2.4.0.201812121631
* Device name: Enerwave ZWN-RSM2-PLUS
* Device version: ?
* Link to [database]: https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/465

[issueFiles.zip](https://github.com/openhab/org.openhab.binding.zwave/files/2678106/issueFiles.zip)

**Comment by cdjackson** [comment]
I think the problem is that the device doesn't report that it supports configuration in it's NIF, so the binding therefore doesn't know that it can be configured. I will update the database to resolve this.
