### ISSUE TITLE
An indication in the device specifications which association group is "Lifeline"

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [openhab/org.openhab.binding.zwave#1093]
It would be helpful if the devices specification could include also information on which association group is to be consider the lifeline group, i.e. the group to which all states changes and automatic sensor reports are sent. It is usually group 1, but not always. 
It would then be great if the binding could set the association up upon inclusion based on this information.

**Comment by cdjackson** [comment]
Sorry - what do you mean by "device specifications"? Where do you want to see this? This sort of information is normally in the device manual.

It will ALWAYS be group 1 for a ZWave+ device. Old devices may be different though.

> It would then be great if the binding could set the association up upon inclusion based on this information.

This is already how the binding works.

I suggest that this sort of question might be better discussed on the forum?

**Comment by FredrikKarlssonSpeech** [comment]
I have had to set all associations myself to be honest. I am on 2.4 M5.

What I was suggesting was a flag in the device database to indicate which group is lifeline. Perhaps this is somehow already present, but I have not noticed since included devices' lifeline was not set to the controller for me.

**Comment by cdjackson** [comment]
The database already includes this, and the binding will definately set the lifeline automatically on initialisation. There are problems however with the UI, and if the UI sends invalid data then it can cause the removal of associations.

I will close this.
