### ISSUE TITLE
Wrong logging level

### ISSUE THREAD

**Issue by paulianttila** [openhab/org.openhab.binding.zwave#1094]
```
2018-12-21 22:14:50.467 [INFO ] [ommandclass.ZWaveVersionCommandClass] - NODE 45: Command Class COMMAND_CLASS_SWITCH_MULTILEVEL has version 0!
2018-12-21 22:14:50.948 [WARN ] [class.ZWaveMultiInstanceCommandClass] - NODE 45: Unknown version 0 for command class COMMAND_CLASS_MULTI_CHANNEL (0x60)
```

User can't do anything about those, so I think logging level should be DEBUG.

Z-Wave binding version: 2.4.0

**Comment by cdjackson** [comment]
This indicates that there is something wrong with the system, and I think WARN is correct -:

warn logging should only be used to inform the user that something seems to be wrong in his overall setup, but the system can nonetheless function as normal, while possibly ignoring some faulty configuration/situation. It can also be used in situations, where a code section is reached, which is not expected by the implementation under normal circumstances (while being able to automatically recover from it).

**Comment by lolodomo** [comment]
I see a lot of logger.warn and logger.error in the binding code,  certainly too much if we consider the code guidelines. 

https://www.openhab.org/docs/developer/guidelines.html#f-logging

logger.error is normally reserved to the framework for example.
