### ISSUE TITLE
Horstmann SES302/SES303 temperature/humidity sensors with external thermometers

### ISSUE THREAD

**Issue by justinasjaronis** [openhab/org.openhab.binding.zwave#1108]
It seems there is some support for this device:  https://www.vesternet.com/z-wave-secure-ses302-temperature-humidity-sensors

However it is possible to connect up to 4 external sensors which would measure pipes temperatures. 
https://www.planete-domotique.com/notices/S/E/SEC_SES002_M.pdf

I'm sure I wired everything correctly, tried removing and adding to network the sensor many times, but I only get  internal temperature and humidity sensor. 

I believe channels for external thermometers are missing in the config file of this sensor: 
https://github.com/openhab/org.openhab.binding.zwave/blob/05d08c332c7967786c76683d17f01b59de22ac31/ESH-INF/thing/horstmann/ses303_0_0.xml

* OH2 Version: 2.4.0
* Binding Version (if SNAPSHOT, provide compile time as found on the filename in the console): 2.4.0

* Device name: SES 303 (with  two SES 002 thermometers ) 
* Device version: 1.1
* Link to [database](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list): https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/782
* If the device is not in the database, provide a link to the manual.

**Comment by cdjackson** [comment]
Please see information on updating the database here -:

https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide
