### ISSUE TITLE
OH2 on Alpine crashes when loading the ZWave binding (libNRJavaSerial.so not linked with musl)

### ISSUE THREAD

**Issue by MFornander** [openhab/org.openhab.binding.zwave#1132]
* OH2 Version: 2.4, 2.5-M1, 2.5-snapshot

I've tried all day now to get OH running on Alpine.  I've tried Alpine 3.8/3.9, OH2.4/2.5m1/2.5snapshot.  I started using a VirtualBox with Alpine guest but moved on to an Intel NUC to verify this issue.  I tried inside docker and without.  Right now I replicated it on an Intel NUC, Alpine 3.9, openJDK8, and the OpenHAB2.4 download zip (no docker).

The error is the same and replicated when trying to configure the ZWave device: Adding the OpenZWave Binding, Inbox->Choose binding->ZWave Binding->ZWave Serial Controller

I have confirmed access to my ZWaveStick by building and running OpenZWave-Control-Panel and it works fine.  I have set permissions to 777 on /dev/ttyACM0 to be sure there are no access problems.

At the ZWave configuration screen, the OH CLI console immediately exits with:
openhab> #
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00000000000036f6, pid=12902, tid=0x00007fb199b8cb10
JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-b12)
Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
Derivative: IcedTea 3.10.0
Distribution: Custom build (Tue Jan  8 12:55:26 UTC 2019)
Problematic frame:
C  0x00000000000036f6
An error report file with more information is saved as:
/opt/openhab2/userdata/hs_err_pid12902.log

I've also attached the full hs_err_pid log file that shows the last frame being
gnu.io.RXTXCommDriver.testRead

After adding the ZWave Binding I see a /userdata/tmp/libNRJavaSerial_root_0 folder appear with a 
libNRJavaSerial.so shared library in it.  This shared library seems to depend on glibc which is not provided by Alpine since it's musl based.

I'm going to give up and switch to a Debian based system for OpenHab but I see in various places that other people are trying to run OH2 on Alpine containers.  OH2 is even provided as Alpine docker containers that i started with but they have all the same problem when activating ZWave with the erroneous libNRJavaSerial being loaded.  I wish I had more time to dig in and find out how to rebuild and supply a musl built libNRJavaSerial but I just want to get OH up and running at this point :)

[hs_err_pid12519.log](https://github.com/openhab/org.openhab.binding.zwave/files/2862664/hs_err_pid12519.log)

**Comment by cdjackson** [comment]
I would suggest that you discuss this on the openHAB forum. I don't think this is really related to the ZWave binding since the serial driver is also not part of the binding.

Note also that you talk about openZWave - the binding does not use this at all.
