### ISSUE TITLE
[Doc] More detailed documentation

### ISSUE THREAD

**Issue by lsiepel** [openhab/org.openhab.binding.zwave#1139]
It would be really helpfull if the documentation would add some examples about textual Thing declaration. And would it be possible to add the usb controller as some sort of bridge? Or how can we set this up by textual configuration?

**Comment by cdjackson** [comment]
Please see the link below.
https://community.openhab.org/t/zwave-manual-thing-configuration/26542

It would be great if you could propose a PR to update the documentation.

**Comment by cdjackson** [comment]
Closing this. If someone wants to update the docs a PR is always welcome.
