### ISSUE TITLE
Problem with wintop_wtrfid_00_000 (Zipato) Events

### ISSUE THREAD

**Issue by RobertHerter** [openhab/org.openhab.binding.zwave#1145]
With 2.5 Build 1538 i have Problems with the WTRFID (Zipato/Wintop)
The notification_access_control channel is switching from 0 (Home) to 255 (Away)
and not 5 and 6 this is problematic because it changes to 0 on every Wakeup (Automatic or tamper).

I add the Log an xml for reference.

[zwave.log](https://github.com/openhab/org.openhab.binding.zwave/files/2914215/zwave.log)

[network_c8e3de92__node_139.txt](https://github.com/openhab/org.openhab.binding.zwave/files/2914227/network_c8e3de92__node_139.txt)

**Comment by cdjackson** [comment]
Alarms should never use values like 5 and 6 - they should normally be On and Off (ie binary).
