### ISSUE TITLE
Zwave controller did not update status

### ISSUE THREAD

**Issue by thomas-tri-tran** [openhab/org.openhab.binding.zwave#1189]
OH2 version : 2.4
Device: aeotec gen 5 zwave controller
Binding: ZWave binding
OS: Openhabian on raspberry PI 3+

Behavior: After certain period  2-3 weeks, the Zwave controller unable to capture the sensor data until restart the openhab services.

**Comment by cdjackson** [comment]
You will need to provide more information and logs. I also suggest to use a more recent version as 2.4 is very old.

**Comment by cdjackson** [comment]
Closing this as no information was provided. If the problem persists, please reopen and provide the requested information.
