### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by tmrobert8** [openhab/org.openhab.binding.zwave#1197]
Very minor - but if you are making any changes, you might want to fix this:

```Status: OFFLINE - COMMUNICATION_ERROR Serial Error: Port {0} is in use```

Notice the "{0}" in the error message..

**Comment by lolodomo** [comment]
I will propose a fix.

**Comment by lolodomo** [comment]
It is a duplicate of #1014.
Can be closed.
