### ISSUE TITLE
DEAD/FAILED Node

### ISSUE THREAD

**Issue by KostiukovAleksey** [openhab/org.openhab.binding.zwave#1227]
Hello, I would like to know in which cases a node is marked as DEAD/FAILED? 
Quotes from docu: 

> DEAD - A device is considered DEAD if it does not respond to a message three times.

If I understand correctly this functionality should use incrementResendCount() method in ZWaveNode class. But the problem is that the method is never called.

The second thing I would like to mention is that in IsFailedNodeMessageClass class node is never mark as FAILED due to commented line 57.

**Comment by cdjackson** [comment]
I’d suggest to discuss this support question on the community forum.
