### ISSUE TITLE
Wrong parameters Neo Coolcam Neoems02z

### ISSUE THREAD

**Issue by epmsmid** [openhab/org.openhab.binding.zwave#1231]
First: Thanks for the great work for the zwave binding!

I have  a Neo Coolcam motion sensor with temperature sensor.
The previous version without temperature sensor had parameters 1 till 10 and 99.
The new version with temparature version has parameters 1 till 12 and 99:
http://manuals-backend.z-wave.info/make.php?lang=en&sku=NEOEMS02Z

Is it possible to add add the device to/change the database?
This is how the device is recognized:
![image](https://user-images.githubusercontent.com/6618724/64561762-c0abc000-d34b-11e9-9743-c1d977c7d282.png)

Regards,

Eric

**Comment by cdjackson** [comment]
Hi,
Please find information on updating the database below -:

https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

If you have any questions, please discuss on the forum where there are a few database administrators who can help

Cheers
Chris

**Comment by epmsmid** [comment]
Thanks Chris for your quick repsonse.
I'll try the link.
Regards,

Eric
