### ISSUE TITLE
Unkown Device: Zooz ZEN25

### ISSUE THREAD

**Issue by argylelabcoat** [openhab/org.openhab.binding.zwave#1236]
The Zooz ZEN25 double plug appears as Unknown for me, I'm running OpenHabian

* OH2 Version: 2.4.0-1
* Binding Version: binding-zwave - 2.4.0

* Device name: Zooz Double Plug, model ZEN25

* Device version: 1.0d

* Link to [database]: https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/1019

* XML Generated for device:
[network_ee20b6f9__node_8.xml.gz](https://github.com/openhab/org.openhab.binding.zwave/files/3617831/network_ee20b6f9__node_8.xml.gz)

Provide a full debug level log of the problem. Preferably, you should try use the [log viewer](http://www.cd-jackson.com/index.php/openhab/zwave-log-viewer) to see if you can identify the problem.

> 2019-09-16 14:06:45.722 [WARN ] [wave.discovery.ZWaveDiscoveryService] - NODE 8: Device discovery could not resolve to a thingType! 027A:A000:A003::2.0
> 
> 2019-09-16 14:06:45.734 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:6f1cef73:node8' to inbox.

**Comment by cdjackson** [comment]
Please use the latest binding - 2.4 is very old and doesn't support this device.
