### ISSUE TITLE
Database Update Needed for Device 473

### ISSUE THREAD

**Issue by bwosborne2** [openhab/org.openhab.binding.zwave#1244]
As referenced in a forum PM with Chris

A database update is needed to resolve the duplicate channel in the Endpoint

**Comment by cdjackson** [comment]
Please don't post links to private conversations here as it's a bit meaningless.

**Comment by bwosborne2** [comment]
OK, Sorry.

**Comment by cdjackson** [comment]
The database now allows a different channel id and channel type by specifying the format ```channel_id[channel_type]```. See below for the device discussed here.

![image](https://user-images.githubusercontent.com/1041475/71769162-524fc680-2f15-11ea-9c4c-c7fa1464fd1b.png)
