### ISSUE TITLE
Fibaro FGS-213 Switch missing ID=4000

### ISSUE THREAD

**Issue by abrodkin** [openhab/org.openhab.binding.zwave#1286]
I see my Fibaro Smart Switch 2 reports ID=4000 which is not listed in `ESH-INF/thing/fibaro/fgs213_0_0.xml` even though it was added in upstream OpenZWave database back in march 2018 (see https://github.com/OpenZWave/open-zwave/commit/978b74ad28605175a3c2df8a18c94c105cf6560a).

**Comment by cdjackson** [comment]
OpenHAB has no connection at all to openZWave. Please update the openHAB system.

https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide
