### ISSUE TITLE
[zwave] Fibaro FGMS001 with older firmware not recognized in OpenHAB 2.5

### ISSUE THREAD

**Issue by hainsilma** [openhab/org.openhab.binding.zwave#1291]
The FGMS001 with FW 3.2 is working as expected, but the older Firmware revision is not recognized.

Logs related to zwave attached from restart of Openhab, and node4 - the one not working in separate log.

Updating the motion sensor with a newer firmware might be a solution, but as far as I know it requires either a Fibaro base station or sending the sensor to Fibaro for update. Both are not reasonable solutions.

OpenHAB version 2.5.0
zwave binding version 2.5.0
Raspbian Release 10, 4.19.75-v71+

If the problem is associated with a device, please provide the following -:

* Device name: FIBARO Motion sensor FGMS 001
* Device version: 
* Link to [database]: (https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/115)

![Screenshot1](https://user-images.githubusercontent.com/59799766/72321638-19e68000-36ad-11ea-93ac-9d147e391cac.png)

![screenshot2](https://user-images.githubusercontent.com/59799766/72321639-19e68000-36ad-11ea-8ab1-0e8971d8d16a.png)

[zwaveinit.log](https://github.com/openhab/org.openhab.binding.zwave/files/4057745/zwaveinit.log)

[zwaveNode4.log](https://github.com/openhab/org.openhab.binding.zwave/files/4057746/zwaveNode4.log)

[node4.zip](https://github.com/openhab/org.openhab.binding.zwave/files/4057756/node4.zip)

**Comment by cdjackson** [comment]
As you can see in the attributes, the device has not completed the interview (there are no type/IDs for the device). You should wake up the device so it can be discovered.

Please discuss this on the forum if you're unsure about this.
