### ISSUE TITLE
Zwave update logging ClimateControlScheduleCommandClass to DEBUG

### ISSUE THREAD

**Issue by HerzScheisse** [openhab/org.openhab.binding.zwave#1327]
Hey Chris,

is it possible to set this logging to DEBUG? I get quite a few of these entries in my logs.

`2020-05-03 13:29:45.917 [INFO ] [veClimateControlScheduleCommandClass] - NODE 10 reported: Override type: NO_OVERRIDE, ScheduleState: [UNUSED]`

What do you think?

cheers
/Holger

**Comment by cdjackson** [comment]
Agreed - it should be DEBUG - I'll update it tonight.
