### ISSUE TITLE
Copy paste error?

### ISSUE THREAD

**Issue by glance-** [openhab/org.openhab.binding.zwave#1432]
https://github.com/openhab/org.openhab.binding.zwave/blob/995683a0d4bd4ba6effdeb8082749fe28e992b14/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveAlarmConverter.java#L422

Two entries, both with the value 5. Should probably be 6.

**Comment by cdjackson** [comment]
Thanks.
