### ISSUE TITLE
FGFS 101 Unknown Device / missing fgfs101_3_2.xml

### ISSUE THREAD

**Issue by Matsuo3rd** [openhab/org.openhab.binding.zwave#1435]
Why has file named "fgfs101_3_2.xml" been removed from Zwave DB? It prevents my Fibaro Flood Sensor from being detected.

Following upgrade to openHAB 2.5.10 my Fibaro fgfs-101 flood sensor was reporting as "Unknown Device". Paper UI displays it as "Z-Wave Node 035 (010F:0B01:1002:3.2)". It used to work properly with openHAB 2.5. 

Got hint from https://community.openhab.org/t/fgfs-101-firmware-version-3-2-support/12712, something was wrong with Zwave DB.

Downloaded older Zwave binding from CI: org.openhab.binding.zwave-2.5.10-SNAPSHOT.jar which happens to contain "fgfs101_3_2.xml". Now my device is properly detected and operating.

**Comment by cdjackson** [comment]
I'm not sure - possibly someone made some changes and didn't get it reviewed. We'll get this added back in the coming days.
