### ISSUE TITLE
UFairy G.R. Tech - GR-105 valve no longer recognized by the binding 

### ISSUE THREAD

**Issue by SebastianCornea** [openhab/org.openhab.binding.zwave#1443]
* OH2 Version: 2.5.10 Release build
* Device name: GR-105 Valve
* Device version: 0152:0003:0512:0.2
* Link to [database] https://opensmarthouse.org/zwavedatabase/438

The device is no longer recognized by openhab, it appears as unknow node "Z-Wave Node 028 (0152:0003:0512:0.2)". It seems that there is some issue with the device DB as on OpenSmartHouse the device definition contains errors. 

Is there a way to quick fix this on my setup?

**Comment by cdjackson** [comment]
I'm not sure why this hasn't exported. There are two versions in the database (0-10, and 10 upward) but for some reason it seems that the lower version (as you have) is not exporting.,

**Comment by SebastianCornea** [comment]
Can I fix it manually on my setup somehow?

**Comment by SebastianCornea** [comment]
It seems that Scott Rushworth just fixed the DB entry.

**Comment by cdjackson** [comment]
Ok, I guess you have another thread open somewhere - please avoid cross posting issues in multiple places.
