### ISSUE TITLE
Link to adding Z-Wave device to database is broken - Adding "Secure SSP-301"

### ISSUE THREAD

**Issue by jackchallen** [openhab/org.openhab.binding.zwave#1471]
The page master/doc/things.md refers to [https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide](Your site), but the site layout appears to have changed, and I can't see a way to submit new devices. FWIW I'm trying to add a Secure SSP-301, which is a simple on/off UK switching mains power socket. The info from the binding is below, but ISTR you needed more information:

zwave_beaming | true
zwave_class_basic | BASIC_TYPE_ROUTING_SLAVE
zwave_class_generic | GENERIC_TYPE_SWITCH_BINARY
zwave_class_specific | SPECIFIC_TYPE_POWER_SWITCH_BINARY
zwave_deviceid | 1
zwave_devicetype | 14
zwave_frequent | false
zwave_listening | true
zwave_manufacturer | 89
zwave_neighbours |  
zwave_nodeid | 22
zwave_plus_devicetype | NODE_TYPE_ZWAVEPLUS_NODE
zwave_plus_roletype | ROLE_TYPE_SLAVE_ALWAYS_ON
zwave_routing | true
zwave_secure | false
zwave_version | 1.0

**Comment by cdjackson** [comment]
This link is out of date - please refer to the main readme page that describes the database.

https://github.com/openhab/org.openhab.binding.zwave#z-wave-device-database
