### ISSUE TITLE
Donexon varmo TZ pro - (aka Danfoss Thermostat) not in database

### ISSUE THREAD

**Issue by HHausmann** [openhab/org.openhab.binding.zwave#1479]
Hi,
"Donexon varmo TZ pro" is not in database.
it looks like Danfoss MT02650 Devolo Thermostat (09356) and is online in oH 2.5.11, but it is still declared as "Unknown Device"

* OH2 Version: 2.5.11-1
* Binding Version (if SNAPSHOT, provide compile time as found on the filename in the console): 2.5.11

* Device name: Donexon varmo TZ pro
* Device version: 1.0
* Link to [database](http://opensmarthouse.org/zwavedatabase): NOT IN DB
* If the device is not in the database, provide a link to the manual. https://www.donexon.com/energie/thermostate/26/heizkoerper-thermostat-varmo-tz-pro?c=41 

thx, holger

[network__node_20.xml.txt](https://github.com/openhab/org.openhab.binding.zwave/files/5743356/network__node_20.xml.txt)

**Comment by cdjackson** [comment]
This is a rebranded devolo so I've updated the current MT02650. It will be in the snapshots in a few days time.
