### ISSUE TITLE
Add Vision ZS6301 to Database

### ISSUE THREAD

**Issue by fleischtorte** [openhab/org.openhab.binding.zwave#160]
Hi Chris,

could you add the Vision ZS6301 CO Detector to the Database? 
On http://www.cd-jackson.com my username is fleischtorte, so please unlock my account that i can add the openhab2 xml.

thanks for your great work!
David

**Comment by cdjackson** [comment]
Hi,
I’ve updated your access - any problems, just yell.

Cheers
Chris

**Comment by fleischtorte** [comment]
Hi Chris,
i uploaded my openhab2 xml and the device manual, is this all i have to do? Thanks for your fast response :)

**Comment by cdjackson** [comment]
Yes - that’s fine unless there are any configuration parameters or association groups which will need to be added manually….  After that I’ll move it into the binding tonight...

Cheers
Chris

**Comment by cdjackson** [comment]
Was added with https://github.com/openhab/org.openhab.binding.zwave/pull/162
