### ISSUE TITLE
Unknown device - Remotec Z-Wave Plus Dimming Switch Module (Dual mode) - Model ZDS-220NA 

### ISSUE THREAD

**Issue by abbasmfazal** [openhab/org.openhab.binding.zwave#1691]
* OH2 Version: openHAB 3.1.0 Release Build
* Binding Version (if SNAPSHOT, provide compile time as found on the filename in the console): 3.1.0

If the problem is associated with a device, please provide the following -:

* Device name: Remotec Z-Wave Plus Dimming Switch Module (Dual mode) - ZDS-220NA
* Device version: 1
* Link to [database](http://opensmarthouse.org/zwavedatabase):  Not in the database 
* If the device is not in the database, provide a link to the manual: https://cdn.shopify.com/s/files/1/0067/9814/7669/files/Remotec_USER_Manual_ZDS-220NA.pdf
* * If there is an XML being generted for the device (in the /userdata/zwave folder), please provide it.
[network_f3f71acf__node_59.zip](https://github.com/openhab/org.openhab.binding.zwave/files/7653519/network_f3f71acf__node_59.zip)

Provide a full debug level log of the problem. Preferably, you should try use the [log viewer](https://www.opensmarthouse.org/utilities/logviewer/zwave/) to see if you can identify the problem.

2021-12-01 22:57:45.735 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:9684715332:node59' to inbox.
2021-12-01 22:57:51.847 [WARN ] [wave.discovery.ZWaveDiscoveryService] - NODE 59: Device discovery could not resolve to a thingType! 5254:8200:8131::1.0

If a device will not initialise, ensure the log is provided from the time OH starts.

Thank you.
(https://github.com/openhab/org.openhab.binding.zwave/files/7653517/network_f3f71acf__node_59.zip)

**Comment by cdjackson** [comment]
Hi.
You can add your device to the database - please see the link below.

https://opensmarthouse.org/blog/zwave_device_database_guide
