### ISSUE TITLE
Add support for setting default tone in COMMAND_CLASS_SOUND_SWITCH 

### ISSUE THREAD

**Issue by kennetn** [openhab/org.openhab.binding.zwave#1775]
For the Aeotech doorbell it would be nice to be able to change the tone played when the doorbell is activated from the remote button (ringer).

Currently the COMMAND_CLASS_SOUND_SWITCH does not support changing default tone with the CONFIGURATION_SET command.
The CONFIGURATION_SET command is used to set both volume and default tone.
The COMMAND_CLASS_SOUND_SWITCH allows setting the volume by setting the default tone as 0 indicating that it should not be changed when the volume is changed. 0 is specified to always be ignored so this is fine.

To change the default tone we can use 255 as volume to prevent it from changing volume, but there is still an issue with this. 
For some strange reason the Z-ware specification says that when you use the value 255 (0xFF):
>This value MUST indicate to restore most recent non-zero volume setting.
>This value MUST be ignored if the current volume is not zero (0x00). This value MAY be used to set the Default Tone Identifier and do not modify the volume setting

So you can modify "Default Tone Identifier" without changing volume if the volume is not 0.
But if the volume is 0 and you change default tone then it will change volume also. (I tested this and the Aeotech Doorbell does works this way)

I would not consider this a big issue because I guess most people will not have the doorbell muted and it would only affect them if they change the tone while muted. Not a very typical scenario I guess.
However I still tried looking for a solution and the specification says this about volume values:
>All other values are reserved and MUST NOT be used by a sending node. Reserved values MUST be ignored by a receiving node.

Because the reserved values should be ignored by a receiving node, I tried going outside specification and sending 254 in the hope that the doorbell would ignore the value just as we would like. However it turns out that the Doorbell does not follow spec here. It will still set volume to 84 :frowning: So this is not an option.

So we can either 

1. Ignore the issues for now
2. Change to remember the last received volume and resend that when the tone need to be changed. But I am a bit unsure how to to that. 

@cdjackson  What is your opinion on this ?

**Comment by cdjackson** [comment]
> Change to remember the last received volume and resend that when the tone need to be changed. But I am a bit unsure how to to that.

This is probably the best, but not 100% reliable. If you store the last known volume in the command class (as a field) then it will be persisted in the XML file and therefore retained "forever" - unless the XML gets lost. If the XML is lost, then the reinitialisation should retrieve the value from the device and store it back in the command class...

Does that make sense? I think this should be easy - and assuming of course I fully grasp the issue :)
