### ISSUE TITLE
Aeotec ZWA001 Bulb 6 Multi-White stopped working after upgrade from 3.2 to 3.3

### ISSUE THREAD

**Issue by robbert0h** [openhab/org.openhab.binding.zwave#1781]
Hello,

Registering this for reference. I have been advised a db update can solve this and I'm intending to try to make such update.

After upgrading from OH 3.2 to 3.3, my Aeotec ZWA001 Bulb 6 Multi-White stopped working:
`Thing 'zwave:device:512:node34' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_CONFIGURATION_PENDING): {config_82_2=The value 6500.0 does not match allowed parameter options. Allowed options are: [ParameterOption [value="5000", label="Cold White (0x1388 (5000k) ~ 0x1964 (6500k))"]]}`

This field is not editable in the UI.

* Device name: Aeotec Limited ZWA001 Bulb 6 Multi-White
* Device version:
* Link to: [database](https://opensmarthouse.org/zwavedatabase/942)

Relevant excerpt from XML:
```
                <entry>
                  <int>82</int>
                  <configurationParameter>
                    <index>82</index>
                    <size>2</size>
                    <value>6500</value>
                    <readOnly>false</readOnly>
                    <writeOnly>false</writeOnly>
                  </configurationParameter>
                </entry>
```

**Comment by cdjackson** [comment]
I've updated the database so that it's not limited to the options..

**Comment by robbert0h** [comment]
@cdjackson: Actually according to the documentation of the bulb this parameter 82 (and also parameter 81) is read only. Why would it make sense to validate the input of read only options at all? Shouldn't the 'read only' flag in the database result in input validation being disabled for a parameter?

**Comment by robkamp** [comment]
I have the same issue. @cdjackson said the database was updated. How do we update the database in OpenHAB 3.3.0?

**Comment by cdjackson** [comment]
You shouldn't need to build the binding yourself - the "scheduled builds" normally happen within minutes of a PR being merged.

**Comment by robbert0h** [comment]
> the [.md file](https://github.com/openhab/org.openhab.binding.zwave/blob/main/doc/aeotec/zwa001_0_0.md) where it says they are 'read only'. Not sure why it says so in there

@cdjackson Still wondering why the parameter 80, 81 and 82 are defined as Read Only in the database. The device manual seems to indicate they should be writable and that kind of makes sense to me reading the descriptions:
<img width="640" alt="Screenshot 2022-07-02 at 23 48 11" src="https://user-images.githubusercontent.com/60843295/177017092-792a4fbc-2547-4c90-8201-b5d9a8904ba4.png">

What do you think?

**Comment by cdjackson** [comment]
Yep - agreed - it looks like they shouldn't be set to read only.  Are you able to change this (I think you have write access to the DB?)

**Comment by robbert0h** [comment]
@cdjackson Yes, will make the change, thanks for confirming.

**Comment by robbert0h** [comment]
@cdjackson Just tested the latest nightly build. As expected, it fixes the original issue I reported (i.e. the `HANDLER_CONFIGURATION_PENDING`). The parameters are still read only, because I made that change after the latest PR/build. Will test the next build once it becomes available.
