### ISSUE TITLE
Neo Coolcam NAS-PD02Z not in database - Z-Wave Node xyz (0258:0200:1036:3.3)

### ISSUE THREAD

**Issue by BitSalat** [openhab/org.openhab.binding.zwave#1807]
Device shows up during Z-Wave scan as unknown device.

Z-Wave Node xyz (**0258:0200:1036:3.3**)

I assume that 0h1036 is an updated version.

Device can be found here: https://www.szneo.com/en/products/show.php?id=197

User manual here: https://usermanual.wiki/NEO-ELECTRONICS/NAS-PD02Z/pdf

[NAS-PD02Z-2887191.pdf](https://github.com/openhab/org.openhab.binding.zwave/files/9638600/NAS-PD02Z-2887191.pdf)

**Comment by cdjackson** [comment]
Please look at the following link on how to update the database -:

https://opensmarthouse.org/blog/zwave_device_database_guide

**Comment by BitSalat** [comment]
I've created a ticket on OpenSmartHouse and added user manual. images and xml from OpenZWave

**Comment by BitSalat** [comment]
Sensor is working now after update of Z-Wave database
