### ISSUE TITLE
Complete partial support of Zwave device: IdLock secure door lock

### ISSUE THREAD

**Issue by espentj** [openhab/org.openhab.binding.zwave#183]
It seems there is a partial compatibility for this device, but it is not working in OH2 atm.
I see it in the Database: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/384 but I am wondering if the XML was made by hand. I am guessing this has to do with that the XML file for the device is not getting produced during the discovery. Here are the details:

Type / Id: 0003:0001
Manufacturer:  0230
Device manual: http://idlock.no/media/wysiwyg/Bruksanvisning/IDL%20Operational%20Manual%20EN%20v1.2.pdf
Link to device in pepper1 database: Not found there

I am guessing understanding why no XML file is generated is a starting point?
I have attached the logfile generated during the inclusion phase. It seems there is a nullpointer occuring. Note it is NODE 13
[Archive.zip](https://github.com/openhab/org.openhab.binding.zwave/files/531610/Archive.zip)

**Comment by cdjackson** [comment]
Currently locks are not supported until the binding rewrite of the lower layers is complete.  I will close this for now and we can address any issues once the security classes are added.
