### ISSUE TITLE
Secure include of door lock not generating xml file

### ISSUE THREAD

**Issue by WSumrell** [openhab/org.openhab.binding.zwave#186]
I am attempting to include a Schlage BE369 lock with the latest snapshot versions of openhab2, zwave, and habmin.  Z-Wave dongle is Aeon Z-Stick S2 with the latest firmware.  I have excluded and included the device and the debug log all seems fine, but the new node never appears in habmin nor do I see a new xml file being generated.

I realize that the Schlage BE369 lock isn't yet in the zwave database, but I read that the xml file should still be generated to assist with the database submission.  

I don't see any reference to "secure" in the log file, which is a bit puzzling.  Including my debug startup and inclusion log and would appreciate any insight.

[dump.txt](https://github.com/openhab/org.openhab.binding.zwave/files/536253/dump.txt)

**Comment by cdjackson** [comment]
Locks are not currently supported so this is expected.
