### ISSUE TITLE
Add Floor thermostat 1.2

### ISSUE THREAD

**Issue by yased** [openhab/org.openhab.binding.zwave#245]
Hi.
Add, please. floor thermostat in OH2 database. It's exist in OH1 database, but no in OH2.

- OH2 Online 2.0.0
- Z-Wave.Me Floor thermostat 1.2
- http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/154
- [node8.xml.txt](https://github.com/openhab/org.openhab.binding.zwave/files/624555/node8.xml.txt)

Thanks.

**Comment by cdjackson** [comment]
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/151
