### ISSUE TITLE
Missing new ProductId for Fibaro gen five devices

### ISSUE THREAD

**Issue by beowulfe** [openhab/org.openhab.binding.zwave#250]
I just purchased a new gen five Fibaro Flood Sensor (FGFS101) and Button (FGPB101). Turns out, they have a new ProductId:
http://products.z-wavealliance.org/products/1642
http://products.z-wavealliance.org/products/2017

Pull request incoming.

**Comment by cdjackson** [comment]
Please don’t just do a PR - it will be overwritten. Please add the update to the database at www.cd-jackson.com.

**Comment by beowulfe** [comment]
Oh, okay. Cancelling the PR.

**Comment by cdjackson** [comment]
Thanks.

You need to register to edit, and then email me (although if you do it in the near future I’ll keep an eye out for the registration email and will update your access straight away).

**Comment by beowulfe** [comment]
Thanks, I submitted the updates to the database and requested review. I'll close this here.

**Comment by cdjackson** [comment]
Thanks - I’ll update tonight.
