### ISSUE TITLE
[Transactions + Security] NodeSerializer delete not working

### ISSUE THREAD

**Issue by pizerg** [openhab/org.openhab.binding.zwave#265]
I think the method signature is not correct

`public boolean DeleteNode(long homeId, int nodeId)`

should be

`public boolean DeleteNode(int homeId, int nodeId)`

Otherwise the filename formatter adds a bunch of "ffffffff" before homeId not matching the correct file on the filesystem so instead of something like "network_cd8afbd8__node_2" we get something like "network_ffffffffcd8afbd8__node_2"

**Comment by pizerg** [comment]
I'm going to close this as it's already been fixed

**Comment by cdjackson** [comment]
Thanks.
