### ISSUE TITLE
FLiRS nodes do not initialize

### ISSUE THREAD

**Issue by jspuij** [openhab/org.openhab.binding.zwave#273]
I've noticed that with the master branch, my FLiRS siren does not start to initialize. The controller reports this node as failed, so I guess initialization is not started, but a FLiRS node never sends a wakeup message. So despite of the failed node state, you have to start sending messages to this node to start the initialization process. Have to dig a bit deeper to confirm this though.
OZCP initializes the node without any problems.

**Comment by cdjackson** [comment]
I wouldn’t advise spending any time on this - there’s a major rewrite coming and initialisation is pretty much totally rewritten.

**Comment by cdjackson** [comment]
I should add that in the new system, my FLiRS device (i.e. a lock) works fine...

**Comment by jspuij** [comment]
@cdjackson That's your transaction-refactoring branch right? Want me to have a go at it and test? Still have a 30+ node network running here ;-)

**Comment by cdjackson** [comment]
Sure - feel free. Any feedback would be welcome…
