### ISSUE TITLE
Add channel sensor_co

### ISSUE THREAD

**Issue by jongj** [openhab/org.openhab.binding.zwave#277]
Device [popp co detector](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/456) has a SENSOR_MULTILEVEL that reports the level of carbon monoxide. At the moment this is mapped to channel alarm_co. I would like to change this to sensor_co, but that channel is not yet available. Could you please add the channel_co?

**Comment by cdjackson** [comment]
Done…
