### ISSUE TITLE
Add support for manufacturer specific command classes

### ISSUE THREAD

**Issue by cdjackson** [openhab/org.openhab.binding.zwave#299]
Support is needed for manufacturers that implement custom command classes. This needs to be configurable to allow different implementations for different devices.

**Comment by mstormi** [comment]
Log to show proprietary lamella tilt control on FGRM-222
[FGRM-222.zip](https://github.com/openhab/org.openhab.binding.zwave/files/732374/FGRM-222.zip)

**Comment by cdjackson** [comment]
This is now implemented in the development branch.
