### ISSUE TITLE
Product to be added to the database: Fibaro FGS-213 (Single Switch 2)

### ISSUE THREAD

**Issue by Phil2015** [openhab/org.openhab.binding.zwave#305]
Hi there!

I am asking if there is any possibility of adding the Fibaro Single Switch 2 (FGS-213) to the zwave database?
I'm using openHAB 1.8.3 with latest snapshot of zwave and the switch is not listed in the database yet.

The product shows up as: Device ID 1000 - Device Type 403
There are FGS-211 and FGS-212 (previous versions of the Single Switch) in the database (FGS-212: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/114)

Any help you be appreciated. 
And I do hope that I catched the right spot where to mention it....

Phil

**Comment by espentj** [comment]
Just for your information. This swtich works fine in Openhab2. I run the FGS213 Single Switch there without any issues.

**Comment by Phil2015** [comment]
Thank you for the information! 
I have a 1.8 setup and don't want to switch to OH2 until there is a final release...

**Comment by cdjackson** [comment]
This issue list is only for OH2 - can you open an issue on OH1 issue and I’ll add it when I get a chance (next week).
