### ISSUE TITLE
[zway] Z-Wave ZHC5010 not recognized in OH2 RC1 in zway binding

### ISSUE THREAD

**Issue by rhjensen79** [openhab/org.openhab.binding.zwave#316]
Z-Wave ZHC5010 is not recognized in OH2 RC1.
The version used is : ZHC5010-WH-4L
It should already be present in the z-wave database, but it's not recognized, by some strange reason.
Links : https://youcontrol.dk/media/wysiwyg/ZHC5010_datablad_1.pdf
Information from OH2.
￼
![skaermbillede 2017-01-20 kl 13 06 17](https://cloud.githubusercontent.com/assets/24954205/22149175/b0391c66-df12-11e6-8253-9091ffb5b363.jpg)

**Comment by cdjackson** [comment]
If this is for the zway binding (rather than the zwave binding) then it probably needs to be in the main OH2 addons issues since zway doesn’t use this database.

**Comment by rhjensen79** [comment]
Why did you close it ?
It's not for the way binding. I'm using the zwave binding, so i don't understand, why this is not the right place to place the issue ?

**Comment by cdjackson** [comment]
Ok - I closed it because you said "zway binding". The zway binding is a different binding. I've just closed your latest one for the same reason - if you are using the zwave binding then please just reopen it (but please change the title so it's clear).
