### ISSUE TITLE
[zwave] Z-Wave ZHC5010 not recognized

### ISSUE THREAD

**Issue by rhjensen79** [openhab/org.openhab.binding.zwave#317]
Z-Wave ZHC5010 is not recognized in OH2 RC1.
The version used is : ZHC5010-WH-4L
It should already be present in the z-wave database, but it's not recognized, by some strange reason.
Links : https://youcontrol.dk/media/wysiwyg/ZHC5010_datablad_1.pdf
Information from OH2.

![skaermbillede 2017-01-20 kl 13 06 17](https://cloud.githubusercontent.com/assets/24954205/22173100/1b6f925c-dfb9-11e6-9ecf-f4095b7d7764.jpg)

**Comment by cdjackson** [comment]
Please open this in the openhab2 issues list. This issue list is only for the zwave binding.

**Comment by cdjackson** [comment]
Title updated to remove reference to zway binding.

**Comment by rhjensen79** [comment]
Thanks. It was autocorrect, that changed the name, and i did not see it until i was to late.

**Comment by cdjackson** [comment]
I've updated the database to add your device references. I won't update the binding until next week though.

I would also suggest to reinitialise the device (in HABmin, select the thing and in the tools menu select the reinitialise option). There's clearly something wrong as half the information displayed in your image is invalid.

**Comment by rhjensen79** [comment]
Thanks.

I’m away traveling, so i might not be able to test, it for the next 14 days. But i will test it as soon as i’m back, and the binding is updated.

Thanks for your help.

/Robert

**Comment by cdjackson** [comment]
That’s fine - I’m also away on holiday right now :)

**Comment by cdjackson** [comment]
This should now be resolved so closing. If it's still not working then please reopen.

**Comment by rhjensen79** [comment]
Sorry it's still not being detected. 

Do i need to do anything special, for the binding to be updated with the ned DB information, other than uninstall and reinstall binding ?

![skaermbillede 2017-02-04 kl 11 23 59](https://cloud.githubusercontent.com/assets/24954205/22617739/7a438ce8-eacc-11e6-918e-81aaf2fc62f3.jpg)


![skaermbillede 2017-02-04 kl 11 20 31](https://cloud.githubusercontent.com/assets/24954205/22617714/fce9ab42-eacb-11e6-93e3-c9f53baab203.jpg)

Thanks.

**Comment by cdjackson** [comment]
> Do i need to do anything special, for the binding to be updated

Yes - you need to be running the snapshot version, and you need to install the latest version. It won't update by itself (ie the bindng doesn't read direct from the database - you need to update).

Please discuss on the forum if you're not sure about how to update your system.

**Comment by rhjensen79** [comment]
It seams to be fixed, both by my test, and by others.
link : https://community.openhab.org/t/logicsoft-zhc5010-z-wave-switch-not-recognized-in-openhab/12160/61

Closing issue.

**Comment by cdjackson** [comment]
Thanks.
