### ISSUE TITLE
Aeon ZW096 timeouts on param 33 

### ISSUE THREAD

**Issue by mhilbush** [openhab/org.openhab.binding.zwave#321]
On Jan 15 in this commit, you added parameter 33 to the Aeon ZW096.  I just installed the most current zwave build and I'm now seeing timeouts during initialization when trying to get param 33 on all 4 of my ZW096 devices.

https://github.com/openhab/org.openhab.binding.zwave/commit/10ef8dd4e444e01c15192e3e29350424a2eebce2#diff-2e1986c9d77a03c7bb9029d5d75dac79

I do see this parameter referenced in the Aeon ZW096 spec, although, oddly, it says there is no default value.  If there's no default value, is it possible that you're unable to get the value of this parameter?
<img width="599" alt="screen shot 2017-01-22 at 5 56 21 pm" src="https://cloud.githubusercontent.com/assets/19286354/22186952/214715ce-e0cc-11e6-8a85-56d98dc969f6.png">

My ZW096's are running version 1.3.

**Comment by mhilbush** [comment]
Hmm.  I see there's a write-only checkbox in the "edit parameter" section of the database editor.  Would this be an appropriate use of that checkbox for parameter 33?

**Comment by cdjackson** [comment]
If you send one of these values to it, does it work?  If so, then let’s use the write only option. Otherwise let’s delete it… (I didn’t add this so I’d need to check who did).

**Comment by mhilbush** [comment]
I'm not entirely sure what's supposed to happen when sending it a value.  It's defined as a 4 byte word, which looks like it should contain RGB values (0-255) in bytes 2-4?  Nevertheless, no matter what integer value I put in the field, it generates this single log statement.
```
2017-01-23 07:50:58.705 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 30: Configuration update received
```

I'd be ok with either deleting it, or making it write only.

**Comment by mhilbush** [comment]
I marked param 33 write-only in the db for the time being.

**Comment by cdjackson** [comment]
I've updated the binding with this...

**Comment by cdjackson** [comment]
Can we close this one?
