### ISSUE TITLE
Trying to initialize a new node after cancelling inclusion process

### ISSUE THREAD

**Issue by pizerg** [openhab/org.openhab.binding.zwave#323]
AddNodeMessageClass wrongly initializes a new node when the Inclusion is cancelled via  "doRequestStop" as (at least with razberry controller) the serial message when successfully including a new node and when cancelling is the same -> bytes [0x01, 0x06, 0xNEW_NODE_ID, 0x00].

Haven't tested with RemoveNodeMessageClass but might have the same issue.

**Comment by cdjackson** [comment]
Which branch is this in? The new branch?

**Comment by pizerg** [comment]
Both

**Comment by cdjackson** [comment]
Ok, thanks - is it trying to initialise a node 0? I thought I'd added a check for this, but maybe not in this instance.

**Comment by pizerg** [comment]
It tries to initialize whichever node would be added next, as [0xNEW_NODE_ID] returns the node id that would have been assigned. The protection for node 0 is already on the code

**Comment by cdjackson** [comment]
Do you have a log file showing the frame flow? I’m not exactly sure what the  [0x01, 0x06, 0xNEW_NODE_ID, 0x00] relates to - is this the content of the AddNode message? So the 0x06 is the DONE message?

**Comment by pizerg** [comment]
Sorry I was not clear enough, I do not have the logs right now but if it's neccessary I can generate an example again. The bytes I mentioned come from 
`public boolean handleRequest(ZWaveController zController, SerialMessage lastSentMessage, SerialMessage incomingMessage)` 

and correspond to
```
incomingMessage.getMessagePayloadByte(0)
incomingMessage.getMessagePayloadByte(1)
incomingMessage.getMessagePayloadByte(2)
incomingMessage.getMessagePayloadByte(3)
```
So yes, the 0x06 is the DONE message and the byte 0xNEW_NODE_ID carries the next "available" node id even if the process was cancelled.

**Comment by cdjackson** [comment]
Closing as this is very old and the inclusion code was completely rewritten.
