### ISSUE TITLE
How can we get the IdLock device (door lock) added to the device database (no XML file)?

### ISSUE THREAD

**Issue by espentj** [openhab/org.openhab.binding.zwave#354]
I'm stuck on adding a new door lock device to the latest SNAPSHOT distro of OpenHab2 via the Z-Wave binding. Any pointer or assistance would be greatly appreciated (I have been eagerly awaiting being able to add my Z-Wave lock to my SmartHome setup). Here are the technical data

**OH2 Version/Binding version**: 
SNAPSHOT latest available as of today (10th of Feb 2017).
**Device ID:** 
0216d7a2 (0230:0003:0001:0.0)
**Device is not in the OpenHab device database**
**Link to english manual for the Z-wave interface:** http://idlock.no/media/wysiwyg/Bruksanvisning/IDL%20Operational%20Manual%20EN.pdf
**XML file is not created** in /opt/openhab2/userdata/zwave folder

**Log files:** 
[LogAndEvent-Debug.zip](https://github.com/openhab/org.openhab.binding.zwave/files/766764/LogAndEvent-Debug.zip)

**Comment by cdjackson** [comment]
Locks and security classes are not included in the current binding so this will not work.  This should be available soon so keep an eye on the openhab forum.
