### ISSUE TITLE
List of supported Devices

### ISSUE THREAD

**Issue by helmar74** [openhab/org.openhab.binding.zwave#391]
Hi,

is there a list of supported devices? I just want to know, if a z-wave device is supported before buying.
I'm currently thinking of buying a  Fibaro FIBEFGWPF-102-5. 
I'm also looking for a battery powered ultra sonic sensor, does anyone  know if such a devices is existing?

Thanks a lot

**Comment by cdjackson** [comment]
You can look at the database http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list
