### ISSUE TITLE
HS-WD100+ Z-Wave Wall Dimmer Brightness level not updating

### ISSUE THREAD

**Issue by yp87** [openhab/org.openhab.binding.zwave#4]
Hi!

I am using an HS-WD100+ z-wave wall dimmer with openhab2 and configured it through Habmin2.
The issue is that I do not receive updates on the brightness level channel, I only receive them on the scene channel. 

Logs:
[ZwaveNode3Dimmed.txt](https://github.com/openhab/org.openhab.binding.zwave/files/392407/ZwaveNode3Dimmed.txt)
[ZwaveNode3Off.txt](https://github.com/openhab/org.openhab.binding.zwave/files/392408/ZwaveNode3Off.txt)
[ZwaveNode3On.txt](https://github.com/openhab/org.openhab.binding.zwave/files/392409/ZwaveNode3On.txt)

Original issue: openhab/openhab2-addons#1037
Thanks!

**Comment by cdjackson** [comment]
I've had a look through the log, and also had a discussion about this device on the forum. It doesn't look like the device sends this information, so it's not possible to update the brightness.

https://community.openhab.org/t/zwave-association-with-no-updates/13399/17
