### ISSUE TITLE
Issues with FGWP102-5

### ISSUE THREAD

**Issue by helmar74** [openhab/org.openhab.binding.zwave#407]
Hi,

I've trouble with a Fibaro FGWP102-5.
I can integrate the Smart Plug in my Z-Wave Network and it's also possible to integrate in OH2. I can switch the plug and measure Watts and kWh. 
This are my problems:
1. kWh are meassured wrong. I plugged in LED's which have 8 Watt power. After 20 minutes 201313 KWh are meassured. I think this is  a wrong value
2. In Habmin no configuration parameters are shown. So its not possible for example to change LED Ring or turn it off.

Screenshot of habmin:
[
![fibaroplug](https://cloud.githubusercontent.com/assets/25499089/24016599/1a806764-0a8d-11e7-9e54-756f193ebaa2.png)
](url)

**Comment by cdjackson** [comment]
As requested, please provide a debug log.

**Comment by helmar74** [comment]
how can i create a log?

**Comment by cdjackson** [comment]
Take a look at the loging section in the docs.

**Comment by helmar74** [comment]
OK, I'll provide a log, but I had to read the  docs first... Will take a while...

**Comment by cdjackson** [comment]
Reading the docs is always useful ;)

**Comment by helmar74** [comment]
of course ;-) but I don't know where i find the docs. so googling around will take time

**Comment by cdjackson** [comment]
http://docs.openhab.org/administration/logging.html <http://docs.openhab.org/administration/logging.html>

**Comment by helmar74** [comment]
Created a DEbug Log.
[openhab_debug.zip](https://github.com/openhab/org.openhab.binding.zwave/files/867065/openhab_debug.zip)

**Comment by cdjackson** [comment]
Closing as being discussed in multiple places.
