### ISSUE TITLE
Wrong parameter constraint of device FGWP102

### ISSUE THREAD

**Issue by flo90** [openhab/org.openhab.binding.zwave#518]
It seems that Parameter 10 has the wrong constraint. Currently 1-10 should be 1-100.
Device: [FGWP102 GEN5 v3.2](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/513)
File: fibaro_fgwp102_3_2.xml

**Comment by cdjackson** [comment]
Please feel free to update the database at www.cd-jackson.com

**Comment by cdjackson** [comment]
I believe this was updated in the database so closing
