### ISSUE TITLE
Creating a function to enable/disable SIS

### ISSUE THREAD

**Issue by RayBe-M** [openhab/org.openhab.binding.zwave#536]
As stated by Chris: 
"I've found how to do it - it's not too hard to enable it actually as it's enabled in the same call as the SUC configuration."
in this thread:
https://community.openhab.org/t/how-to-enable-sis/26323
Thanks

**Comment by cdjackson** [comment]
This is actually already coded - I'd just forgotten I did it ;)

I'll add a new parameter that will replace the true/false for the SUC to allow the three options.

**Comment by cdjackson** [comment]
Hmmm - good and bad news - when the binding sets SUC, it is actually already setting SIS, so nothing to do.
