### ISSUE TITLE
New Sensative Strip Model Number

### ISSUE THREAD

**Issue by thx2000** [openhab/org.openhab.binding.zwave#548]
@cdjackson I'm guessing the old xml will work for this version, but I just received a sensative strip with model #: 11-01-012 Is it possible to just duplicate the existing xml so that it supports this model as well?

**Comment by cdjackson** [comment]
I guess it depends on how different it is.I’ll drop Strips an email - they are pretty quick to respond.

**Comment by cdjackson** [comment]
Sensitive Strips confirm that the -012 version is just the US version of the -011. Please can you provide the XML file that OH generates for this device - or at least provide the device type/id for your version. We can then update the database with this information.

**Comment by thx2000** [comment]
I played with it some more to try to get you those numbers, and it did finally register as is.  I only had it about 3 meters away from the z stick before, but I found I had to be right on top of it to get it to register.  Sorry to waste your time, thanks for your help!!!
