### ISSUE TITLE
Z-Wave: Show Rollershutter Items as 0..100%, not 1..100% 

### ISSUE THREAD

**Issue by michel53** [openhab/org.openhab.binding.zwave#561]
As discussed here https://community.openhab.org/t/oh2-rollershutter-only-1-100-not-0-100/27388/4, in the 2.0 Z-Wave binding, rollershutters are shown as 1..100%.
In the 1.9 binding, they were shown (correctly) as 0..100%.
Since Z-Wave does not provide a 100% value, there should be some conversion.

**Comment by cdjackson** [comment]
This indicates that 0% is not possible, and this isn't the case. There is nothing stopping the switch from showing a range of 0 to 100% - if the value is 99%, then it is changed to 100%, so 99 is the only value that can't be shown.

I'll close this - please continue the discussion on the forum as this might be calibration which I can not help with.
