### ISSUE TITLE
Add Yale (Assa Abloy) YRD246 to database

### ISSUE THREAD

**Issue by TheKorn2** [openhab/org.openhab.binding.zwave#569]
Added to the zwave database, hopefully time to just wave the magic wand.  ;)

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/594

**Comment by cdjackson** [comment]
I'll try and remember to update the dev binding tonight ;)

**Comment by TheKorn2** [comment]
What's weird is that the device in the database says support security = NO, then talks about security classes.  (It for sure does security, and in habmin it says it's doing security, so...  ?????  Maybe I'm not reading that right?)

**Comment by cdjackson** [comment]
Yeah - I’m not 100% sure what that refers to. It’s something that’s read from the device and displayed in the data - it’s not used for anything though so don’t worry about it...

**Comment by TheKorn2** [comment]
Wand has been waved, lock works great.  Thanks!
