### ISSUE TITLE
Can't exclude Yale YRD246 secure lock

### ISSUE THREAD

**Issue by TheKorn2** [openhab/org.openhab.binding.zwave#573]
Openhab2 security development binding.  Yale YRD246 lock includes just fine, but if you try and exclude it the lock immediately fails the exclusion (within 3 seconds of completing the exclude keypresses on the door lock).

This ticket is just for documentation purposes, in case someone else has the same problem and is googling.  No action necessary.

**Comment by TheKorn2** [comment]
Root cause is a bug in the controller, an older aeon z-stick 2 in this case.  Upgrading firmware to v3.08, lock successfully (and quickly!) excluded.

**Comment by cdjackson** [comment]
Thanks for posting - it’s good to have the reference.
