### ISSUE TITLE
Database Update #257 leads to wrong detection of everspringAN180 

### ISSUE THREAD

**Issue by hmerk** [openhab/org.openhab.binding.zwave#589]
DB Update changed the xml file for AN181 to
```
-      <property name="manufacturerRef">0004:0006</property>
 +      <property name="manufacturerRef">0004:0006,0004:0007</property>
```
As AN180 is recognised as 0004:0007, after above changes, it is recognised as AN181, which is wrong.

**Comment by cdjackson** [comment]
I've updated the database to remove the 0004:0007

**Comment by hmerk** [comment]
Thanks @cdjackson !!!
