### ISSUE TITLE
Philio PSP05 Motion Sensor - Add configuration definitions to database

### ISSUE THREAD

**Issue by mfkeenan** [openhab/org.openhab.binding.zwave#630]
The current definition of the Philio PSP05 Motion Sensor does not appear to have many of the configuration parameters allowed by the device in the database.

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/600

Manual is attached and configuration parameters extracted to image below for convenience.
![image](https://user-images.githubusercontent.com/29838452/27770860-3a4f39c0-5f3e-11e7-931f-2aefd1f1c8ad.png)

Cheers
Mark

[z_wave_philio_motion_sensor_psp05_gen5_manual.pdf](https://github.com/openhab/org.openhab.binding.zwave/files/1117856/z_wave_philio_motion_sensor_psp05_gen5_manual.pdf)

**Comment by cdjackson** [comment]
Please consider updating the database to add the parameters. This will be much quicker than waiting for someone else to do it.

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

**Comment by sihui62** [comment]
Adding them by yourself is simple:

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

Open an account, email Chris for edit rights and you are good to go.

**Comment by mfkeenan** [comment]
Thanks guys. Be happy to do it myself. Just created and account and mailed Chris for access.

**Comment by cdjackson** [comment]
Closing this as it should be managed directly into the database...
