### ISSUE TITLE
Kaipule IM20_ZWAVE_EU not showing in Database

### ISSUE THREAD

**Issue by Uruwashii** [openhab/org.openhab.binding.zwave#656]
The EU version of the Kaipule IM20_ZWAVE door contact sensor is not showing in the device database.

IM20_ZWAVE is being discovered as Z-Wave Node 4 (0214:0002:0001:5.38)

Purchased Thing: IM20_ZWAVE_EU

THING PROPERTIES
zwave_class_basic
ROUTING_SLAVE
zwave_class_generic
SENSOR_NOTIFICATION
zwave_frequent
false
zwave_neighbours
1,3
zwave_version
5.38
zwave_listening
false
zwave_plus_devicetype
ACCESS_CONTROL_SENSOR
zwave_deviceid
1
zwave_nodeid
4
zwave_routing
true
zwave_beaming
true
zwave_class_specific
NOTIFICATION_SENSOR
zwave_manufacturer
532
zwave_devicetype
2

**Comment by cdjackson** [comment]
This device is only partially populated -:

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/254 <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/254>

Please see the guide on updating the database -:

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide>
