### ISSUE TITLE
Offer more frequent polling options

### ISSUE THREAD

**Issue by jjhuff** [openhab/org.openhab.binding.zwave#658]
For devices that don't support Hail/Associations, it'd be handy to have more frequent polling options in the UI. The current minimum (in the UI) is 10min.

FWIW, my SmartThings hub polls these devices every 10sec or so.

**Comment by cdjackson** [comment]
Currently the minimum is 10 seconds - not 10 minutes. Just type in whatever number you want.

**Comment by openhab-5iver** [comment]
What is the unit for manual entries?

**Comment by cdjackson** [comment]
Seconds.

**Comment by jjhuff** [comment]
Ahh! It wasn't clear that you could type whatever you want in there. Thanks!
