### ISSUE TITLE
How is the device xml file written in the database

### ISSUE THREAD

**Issue by Ynoy** [openhab/org.openhab.binding.zwave#661]
<properties>
      <property name="vendor">AEON Labs</property>
      <property name="modelId">ZW120</property>
      **<property name="manufacturerId">0086</property>
      <property name="manufacturerRef">0002:0078,0102:0078</property>
      <property name="dbReference">405</property>
      <property name="defaultAssociations">1</property>**
    </properties>

Above the black line of four data is how to get it?
How to write the specific document, the equipment will be more perfect fit
Thanks！！

**Comment by cdjackson** [comment]
Database information is found here -:
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

If you want to discuss, please open a thread on the openhab community forum.
