### ISSUE TITLE
Handle multiple versions of Heatit / Multireg thermostat

### ISSUE THREAD

**Issue by mtryfoss** [openhab/org.openhab.binding.zwave#68]
https://community.openhab.org/t/template-default-settings-for-z-wave-device-specific-parameters/13504/26

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/247

Manual for newest firmware:
[Manual_Heatit_Z-Wave_Ver2016-A-juni.pdf](https://github.com/openhab/org.openhab.binding.zwave/files/452028/Manual_Heatit_Z-Wave_Ver2016-A-juni.pdf)

**Comment by cdjackson** [comment]
https://community.openhab.org/t/template-default-settings-for-z-wave-device-specific-parameters/13504

**Comment by cdjackson** [comment]
The additional version has been added to the database so closing.
