### ISSUE TITLE
Aeotech ZW100 MultiSensor 6 and Fibaro FGMS001 Motion Sensor never get update

### ISSUE THREAD

**Issue by arindam2ghosh** [openhab/org.openhab.binding.zwave#69]
I added recently 2 sensors in my Aeotech Z-Stick. But I noticed almost after 1 hour I never get any update from these 2 sensors. Whereas other sensors are ok. I am using zwave binding from Chris Jackson https://github.com/openhab/org.openhab.binding.zwave/commit/6ff67db1f88375b6512d936115cf3b83815f6482

<img width="1182" alt="screen shot 2016-09-02 at 9 12 58 pm" src="https://cloud.githubusercontent.com/assets/2129395/18205302/e4f3f228-7153-11e6-9fa2-e82f22067462.png">

I attached the log message from eclipse IDE zwave binding. 
[log.txt](https://github.com/openhab/org.openhab.binding.zwave/files/452107/log.txt)

What am I doing wrong?

**Comment by cdjackson** [comment]
There's nothing wrong in the log. I would suggest waking up the device and ensuring it is configured correctly (eg wakeup class).

Please can you raise such questions on the forum where there are many people to help answer. The issue list should be used for bugs
