### ISSUE TITLE
 OFFLINE - COMMUNICATION_ERROR zwave.thingstate.serial_notfound

### ISSUE THREAD

**Issue by stevenazari** [openhab/org.openhab.binding.zwave#694]
This issue list is to report bugs or enhancements for the openHAB Z-Wave binding. If you're not sure about something, please consider discussing it on the [forum](http://community.openhab.org) before raising an issue - more people follow the forum than monitor the issues list, so if you are having trouble with a device, or want to ask a question, you will have a much larger audience there.

In order to ensure we have the best information to deal with the issue, please fill in the following information (delete as necessary depending on the issue).

* OH2 Version: stable branch
* Binding Version (if SNAPSHOT, provide compile time as found on the filename in the console):
Latest offered from bindings download in openhab

If the problem is associated with a device, please provide the following -:
* Device name: Aeotec Z-Stick
* Device version: GEN5
* Link to [database](http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list): Couldn't see it in the list.
* If the device is not in the database, provide a link to the manual.
https://aeotec.freshdesk.com/support/solutions/folders/6000146720

* If there is an XML being generted for the device (in the /userdata/zwave folder), please provide it.

Provide a full debug level log of the problem. Preferably, you should try use the [log viewer](http://www.cd-jackson.com/index.php/openhab/zwave-log-viewer) to see if you can identify the problem. I am new to openhab2 could this link not tell me where the file would be located?

I am on a Raspberry Pi 2 (Jessie) withe a fresh install and fresh openHab2 - I have the AEOTEC (AEON?) Z-Wave controller communicating on /dev/ttyACM0

in openHab2 when adding the binding I get: 
  OFFLINE - COMMUNICATION_ERROR zwave.thingstate.serial_notfound

I have seen people try a heap of different things - the permissions of the folder is correct - or at least for the sake of trying it now says:

  ls -l /dev/ttyACM0
  crw-rw-rw- 1 root dialout 166, 0 Sep 24 11:08 /dev/ttyACM0

I have tried both stable and snapshot builds with no success.

**Comment by cdjackson** [comment]
Please discuss this on the forum. This will not be a binding issue, but an issue with your configuration.
Thanks.
