### ISSUE TITLE
New Sensor: Heiman Technology Co. Ltd - DX1CG-Z

### ISSUE THREAD

**Issue by MarcoFre** [openhab/org.openhab.binding.zwave#697]
Hi, please add below gas - CH4 Sensor to OpenHab 2 Zwave binding:
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="zwave"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
  xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0
                      http://eclipse.org/smarthome/schemas/thing-description/v1.0.0">

  <thing-type id="heiman_dx1cgz_00_000" listed="false">
    <label>DX1CG-Z CH4 Gas Sensor</label>
    <description>CH4 Gas Sensor</description>

    
    <channels>
      <channel id="alarm_general" typeId="alarm_general">
        <label>Alarm</label>
        <properties>
          <property name="binding:*:OnOffType">ALARM,BASIC</property>
        </properties>
      </channel>
    </channels>

    
    <properties>
      <property name="vendor">Heiman Technology Co. Ltd</property>
      <property name="modelId">DX1CG-Z</property>
      <property name="manufacturerId">0260</property>
      <property name="manufacturerRef">8003:1000</property>
      <property name="dbReference">682</property>
    </properties>

  </thing-type>

</thing:thing-descriptions>

**Comment by cdjackson** [comment]
This will be added in the near future (hopefully the next few days).
