### ISSUE TITLE
Database update

### ISSUE THREAD

**Issue by asilva732** [openhab/org.openhab.binding.zwave#717]
EDIT: See
https://github.com/openhab/org.openhab.binding.zwave/pull/718
https://github.com/openhab/org.openhab.binding.zwave/pull/719

These things have existing XML files.

Z-Wave Node 5 (0098:1E10:015C:7.4)
CT-30 Thermostat from Radio Thermostat Company of America (RTC)
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/94

Z-Wave Node 6 (0109:2008:0803:1.10)
PID11995 ZWave On/Off Plugin from Monoprice
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/454

The problem seems that the  "Type"/"ID" from my devices don't match the entries in the databases.

**Comment by cdjackson** [comment]
Closing as changes will be incorporated into next database update (later today)
