### ISSUE TITLE
Aeon Multisensor Gen5 (ZW074) is missing in database

### ISSUE THREAD

**Issue by dragondagda** [openhab/org.openhab.binding.zwave#729]
I tried to teachin the following device, but it was only recognized as Unknown Device. Can you add it to the database?

* Device: AEOTEC MultiSensor Gen5
* Model: ZW074-C
* http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/72

Thanks

**Comment by cdjackson** [comment]
The device is already in the database (as you have seen in the link). Please discuss your problem on the openhab community forum stating exactly the issue including what the UI says, if you've woken the device up etc.
