### ISSUE TITLE
NQ-9021 need Update

### ISSUE THREAD

**Issue by bulliuli** [openhab/org.openhab.binding.zwave#731]
Hello,
I have found some errors in the parameter list and already corrected.
I have my info from
https://www.benext.eu/static/manual/northq/power-reader-NQ-9021-EU.pdf

greetings
Uli

**Comment by cdjackson** [comment]
Please see information on updating the database at this link -:
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide
