### ISSUE TITLE
Duwi switch -> impossible to add

### ISSUE THREAD

**Issue by Newtt** [openhab/org.openhab.binding.zwave#752]
When I hit search module in openhab2, there is something like 6-7 node that comes up. This is weird because the battery is not even in into the switch...

When I try to pair my Duwi wall switch (Z-Wave module), but there is something like 5-6 node that appear, Z-Wave Node 10, Z-Wave Node 9, Z-Wave Node 8, Z-Wave Node 7, etc... and when I try to add them, I keep getting errors (no communication error). How can I permanantly delete old nodes / old try to pair the item ?

**Comment by cdjackson** [comment]
If you are seeing multiple nodes, then it means that there are multiple nodes included into the controller - the controller knows if you've included nodes in the past.

I would suggest to read the manual for your controller - it might mention how to reset the stick, or you can use the hard reset option in openhab.

Please discuss this issue on the forum where there are more people to help as this is not a bug in the software.

Thanks.
