### ISSUE TITLE
Color class does not scal colours correctly

### ISSUE THREAD

**Issue by TheNavy** [openhab/org.openhab.binding.zwave#761]
There is an Problem with the Communication between openHAB and my Fibaro RGBW Controller.

Part 1:
I’ve created a Color-Item which links to the Color-Channel of the RGBW-Controller-Thing. Then i created an Colorpicker and want to choose the Color. The Color is correct, but i can't adjust the Brightness -> Always 100%. If i use an Rule to set the Color it works fine!

Here is the LOG with zwave on Debugging:
`11:49:23.034 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'RGBW_Wohnzimmer_Balken_Col' received command 60,84,80
11:49:23.042 [DEBUG] [nding.zwave.handler.ZWaveThingHandler] - NODE 2: Command received zwave:device:6540d643:node2:color_color --> 60,84,80
11:49:23.046 [DEBUG] [nternal.converter.ZWaveColorConverter] - NODE 2: Converted command '60,84,80' to value 80 80 12 for channel = zwave:device:6540d643:node2:color_color, endpoint = 0.`

Part 2:
The Controller sends an Feedback. But the Color is completely wrong. For Example you choose Red as Color the Controller changed to Red (with 100% Brightness) but the Feedback is an completely other Color, so the Colorpicker jumps around.
`11:49:23.611 [DEBUG] [nding.zwave.handler.ZWaveThingHandler] - NODE 2: Updating channel state zwave:device:6540d643:node2:color_color to 330.0,100,100 [HSBType]`

The Full log is Attached: [LOG.txt](https://github.com/openhab/org.openhab.binding.zwave/files/1542594/LOG.txt)

Device name: Fibaro RGBW-Controller
Link: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/131
openHAB-Version: 2.1 Stable & Nightly (from 07.12.17)

Greetings,
Richard

**Comment by cdjackson** [comment]
Closing. The color class was updated to fix scaling - hopefully it covers this. If not, please open a new issue with anything that is remaining.
