### ISSUE TITLE
Star network

### ISSUE THREAD

**Issue by Ynoy** [openhab/org.openhab.binding.zwave#772]
@cdjackson @kabili207 @evansj @maxberger @quadule 
Hi，I want to understand that in the present Zwave code has sets the Zwave network as the star network topology function.ZW_AssignPriorityReturnRoute.ZW_SetPriorityRoute.

**Comment by cdjackson** [comment]
I would suggest to discuss this on the community forum. The issue list is for bugs and this seems like a question (although I don't understand what you are actually asking). 

Please reformulate your question and ask on the forum - feel free to mention me (@ chris on the forum)and I will try and provide an answer. 

Chris
