### ISSUE TITLE
[DEV] Save not enabled for updating zWave Device Configs

### ISSUE THREAD

**Issue by travellingkiwi** [openhab/org.openhab.binding.zwave#778]
* OH2 Version: 2.3.0-snapshot (Build #1151)
* Binding Version : 2.3.0.201712260145

If the problem is associated with a device, please provide the following -:

* Device name: Aeotec Multi Sensor 6

Not limited to the Aeotec multi sensor 6, but I just happen to have 2 of them I can't alter the config for.

When opening the config edit, the save (Blue Tick Button) at the top is disabled. Sometimes I find an existing setting that OH says is invalid and updating that to a 'supported' value enables the save. However on several devices there is no setting highlighted in red to indicate what the save is disabled.

Can we have something that makes it obvious what the issue is stopping the save? Especially since the settings currently in use on those devices are the DEFAULT ones that something (Presumably the zWave binding) initialised.

Note that although raising this against the current DEV (i.e. 2.3.0 snapshot) the same issue affects 2.2.0-1 release.
 
![screen shot 2017-12-27 at 15 26 30](https://user-images.githubusercontent.com/17937579/34385386-6394709e-eb1a-11e7-8870-29d173358888.png)

**Comment by travellingkiwi** [comment]
Note that on one of them, the 'Temperature Threshold' might be responsible. Initially it's blank. And save is Disabled

![screen shot 2017-12-27 at 15 30 40](https://user-images.githubusercontent.com/17937579/34385467-ec71549a-eb1a-11e7-95c7-04bda6fb3a24.png)

Inserting ANYTHING in there appears to 'enable' the save...

![screen shot 2017-12-27 at 15 31 19](https://user-images.githubusercontent.com/17937579/34385478-02645e6e-eb1b-11e7-9825-1da1bce4a574.png)

However unlike other devices where I've had this issue, the default (blank) value wasn't highlighted as an issue (i.e. in Red like some devices)

**Comment by cdjackson** [comment]
I guess there are two issues here, and it’s not directly related to the binding so I’ll close this.

First issue - you want something to make it obvious what is stopping the save - then this is a UI issue and I’d suggest to raise it in the UI you are using (PaperUI?)

The second is if there are issues with the database, then please get an account at the database site (www.cd-jackson.com) and help fix them.

Cheers
Chris
