### ISSUE TITLE
[DEV] Enable SUC in default controller config

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/org.openhab.binding.zwave#795]
https://community.openhab.org/t/oh2-z-wave-refactoring-and-testing-and-security/21653/2305?u=5iver

https://community.openhab.org/t/oh2-z-wave-refactoring-and-testing-and-security/21653/2307?u=5iver

As reported in forum, the default controller settings have SUC disabled. Most people would be setting up systems with a single controller, so I believe SUC should be enabled by default.

**Comment by cdjackson** [comment]
Should now be implemented

**Comment by openhab-5iver** [comment]
Habmin displays this as a 1. Should I open a feature request to change that to Yes/No?

![image](https://user-images.githubusercontent.com/21967853/37257161-b41c9194-253b-11e8-8f09-93258c338e2d.png)

**Comment by cdjackson** [comment]
No - this is a node number…  It allows you to set the node of the SIS and it defaults to the local controller if it’s not set.

**Comment by openhab-5iver** [comment]
Ahhhhh. I read too fast.
