### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/org.openhab.binding.zwave#810]
See https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/259/org.openhab.binding$org.openhab.binding.zwave/testReport/

**Comment by cdjackson** [comment]
This is very strange given there have been no changes to code for a month!

**Comment by kaikreuzer** [comment]
Don't ask me - but it needs to be fixed anyhow ;-)

**Comment by cdjackson** [comment]
Agreed :)

I  think it's probably trigged by something changing in ESH as it's failing to create a thing in a test. I probably won't get the chance to look at this tonight but will check it out tomorrow.

```
ThingType thingType = ThingTypeBuilder.instance("bindingId", "thingTypeId", "label").build();
Thing thing = ThingFactory.createThing(thingType, new ThingUID(thingType.getUID(), "thingId"), new Configuration());
```

**Comment by cdjackson** [comment]
The issue seems to be triggered by a change in Eclipse - for now I've just ignored the tests as I can't debug as tests are not able to be run in the IDE (see #812).
