### ISSUE TITLE
Aeonlab Smart Switch Gen. 5 - Wrong Status after Restart of openhab

### ISSUE THREAD

**Issue by kikig1** [openhab/org.openhab.binding.zwave#816]
Hi Forum ;)

My Aeonlab Smart Switch Gen. 5 is recognized as ZW075 Smart Energy Switch 3rd Edition.
Anything works fine, except after restarting the server. After a restart always the switch is shown as online but as switched off and didn't report energy. I've to switch it off and again on, then the status is correct (on) and i get the energy reports.

I'm very new with openhab and have no idea, what to do.

Did anyone have a tip for me? :)

Many thanks and best regards.
k.

**Comment by cdjackson** [comment]
> Hi Forum ;)

This is not actually the forum - this is the bug tracker :) I suggest to discuss on the actual [community forum](http://community.openhab.org).
