### ISSUE TITLE
HABmin error when new device added "error sending action to the server"

### ISSUE THREAD

**Issue by nbibin001** [openhab/org.openhab.binding.zwave#836]
Hello, I am trying to use the OH Zwave binding withe Razberry GPIO addon board. The binding version I am using is org.openhab.binding.zwave-1.11.0.jar. I installed HABmin , it shows OpenHAB as online. But when I try to include new devices it says "error sending action to the server". Really appreciate any help.

![image](https://user-images.githubusercontent.com/15659590/36421729-ae6eb044-1607-11e8-857e-723cb81b157b.png)

![image](https://user-images.githubusercontent.com/15659590/36421683-832c3190-1607-11e8-9657-a6b4fb495979.png)

![image](https://user-images.githubusercontent.com/15659590/36421777-cb2389e4-1607-11e8-87de-034dfe867bff.png)

**Comment by cdjackson** [comment]
This repository is for OH2 zwave binding. I'd suggest to discuss on the forum (community.openhab.org) - hopefully someone can help you there.
