### ISSUE TITLE
FortrezZ WWA01 and WWA02 Water and Temperature sensors not supported presently

### ISSUE THREAD

**Issue by geoffkerr** [openhab/org.openhab.binding.zwave#839]
OH2 Version: 2.2.0.1 on Raspberry PI running Stretch (manual install, not OpenHABian)
    ZWave Controller: Aeotec ZWave Stick Gen 5
    Device name: FortrezZ WWA01 and WWA02
    Link name: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/222?layout=openhab2
    Manual: https://static1.squarespace.com/static/57363221555986b60e62f0f0/t/580909b259cc68e8127c3405/1476987314957/WWA-01+Spec+Overview-3.pdf

Both devices should behave basically the same with the exception that the WWA01 has a buzzer and the WWA02 has an led to indicate an alarm caused by water.  They report battery levels, sensor status, and temperature.  Additionally, there are advanced settings to tune the temperature ranges to compare above and below to trigger alarm.

**Comment by cdjackson** [comment]
Please update the database at www.cd-jackson.com

**Comment by geoffkerr** [comment]
WWA-02 existed there already.  Cloned it and filled in data for WWA-01.  How can I test these on my local install to make sure that they work?

**Comment by cdjackson** [comment]
If you want to test locally you would need to export the database and recompile your own binding.

I don’t really know what you mean by “cloned it” - there’s no such button in the database and I don’t think the docs mention anything like this?

**Comment by cdjackson** [comment]
The XML you need to upload is the one created by OH - you can’t download one from the database, change it, and upload it again.  If you want to copy configuration from another device, this needs to be done within the database (there’s a menu option to do this) and not by manipulating XML files.

Manufacturers use type/id for all sorts of reasons - sometimes for versions (although there is also a version field available) but more often for different regions, or colours or who knows what… ;)

Are the WWA01 and WWA02 fundamentally the same? If so, we can simply add the new IDs to the existing database entry.

**Comment by geoffkerr** [comment]
Yes, the devices are the same.

**Comment by cdjackson** [comment]
The you should just update the existing entry with the type/id and not add a new database entry.

**Comment by geoffkerr** [comment]
I updated the site to refer to the device as "WWA-01 / WWA-02" and added the updated type/id information.
