### ISSUE TITLE
POPP 9402 Smoke alarm triggers burglar item

### ISSUE THREAD

**Issue by roberlax** [openhab/org.openhab.binding.zwave#901]
Hi,

I have a problem regarding smoke alarms for POPP 9402 Smoke Sensor V1.1:
This device appears in openhab with several channels including burglar and smoke alarm.
I have mapped these channels to items.

The problem is, when I trigger a test smoke alarm at the device, I get reported burglar alarm too (item DGSmokeTamper below ). Burglar alarm itself works fine. 

I have attached the Zwave log file with debug level messages.
At time 21:26:28 smoke alarm starts.
At time 21:26:33 smoke alarm ends.

From the logs I can see e.g. that the incoming message is decoded clearly as "smoke"-report:
21:26:28.013 ... - NODE 44: Sensor Binary report, type=Smoke, value=255
21:26:33.788 ... - NODE 44: Sensor Binary report, type=Smoke, value=0

OpenHAB version 2.2

Item configuration
Switch    DGSmokeSiren ... { channel="zwave:device:eedfa926:node44:switch_binary" }
Switch    DGSmokeAlarm ... { channel="zwave:device:eedfa926:node44:alarm_general" }
Switch    DGSmokeTamper ... { channel="zwave:device:eedfa926:node44:sensor_binary" }

Hope somebody can help me.
regards
[zw.log](https://github.com/openhab/org.openhab.binding.zwave/files/1989323/zw.log)

**Comment by cdjackson** [comment]
As above, please discuss further on the forum if the problem still exists.
