### ISSUE TITLE
Missing meter_reset in FGS223 in same way as in #352

### ISSUE THREAD

**Issue by Barnecke** [openhab/org.openhab.binding.zwave#916]
Hello, 

I found, that with #352 the function "meter_reset" was added to FGRM 222, but I'm new to OH2 and don't know how to add this to the binding für FGS22.

Additionally I'm not sure if the double switch has one reset function for the full switch, or if there are two resets "meter_reset1" and "meter_reset2" for both integrated switches.

Any advise how-to integrate the function in z-wave binding?

**Comment by cdjackson** [comment]
I’ve added this to the database. It will be added to the latest snapshot in the coming days.

**Comment by cdjackson** [comment]
This should now be available once the latest snapshot is built

**Comment by cdjackson** [comment]
Please provide a debug log of the ZWave binding and I’ll have a look.

**Comment by Barnecke** [comment]
I put the full debug log in last post. When activating zwave logging with command:
        log:set debug org.openhab.binding.zwave

I get no entries when activation the item, but in full debug log from last post I see that the item was activated. 
Where is my mistake?

**Comment by Barnecke** [comment]
Ok, I delete the thing and added it again (by script zwave.items), but there is no entry in the log for "node8:meter_reset". Here is the log-file:
[log double switch.txt](https://github.com/openhab/org.openhab.binding.zwave/files/2069567/log.double.switch.txt)

Additionally I tried the same, when using this item for my fibaro wall plug. There the "node7:meter_reset" is added. Please find attached the log-file for comparison:
[log wall plug.txt](https://github.com/openhab/org.openhab.binding.zwave/files/2069572/log.wall.plug.txt)

Hopefully this helps you.

**Comment by cdjackson** [comment]
I’m not sure what you mean by adding it by script?  You need to delete the thing in the UI and add it back again so that it uses the new thing definition.

**Comment by Barnecke** [comment]
The thing in paperUI is not showing meter_reset. Therefore I added the item manually in a .items file.

**Comment by Barnecke** [comment]
The thing in paperUI is not providing meter_reset. Therefore I added the item manually in a .items file.

⁣Gesendet mit BlueMail ​

**Comment by cdjackson** [comment]
Did you delete the thing in paper UI and add it back again?you must do this to get the new definition. 

Adding the items to channels that don’t exist definitely won’t work.

**Comment by Barnecke** [comment]
Hi, I'm back again :-)

Yes, I delete the thing and added it again, but the parameter still not there. Here is the zwave-log, when adding the thing again:
[log add double switch.txt](https://github.com/openhab/org.openhab.binding.zwave/files/2073653/log.add.double.switch.txt)

Also the bundle shows the correct version:
openhab> bundle:list | grep ZWave
245 │ Active    │  80 │ 2.2.0                  │ ZWave Binding
254 │ Installed │  80 │ 2.4.0.201806030817     │ ZWave Binding

Any more hint?
THX

**Comment by cdjackson** [comment]
You are not running the correct binding. You have the 2.2 version running, not the latest version with the changes. 

Please discuss this on the forum if you don’t understand how to fix this.

**Comment by Barnecke** [comment]
OK, this was my fault :-)

I deleted the 2.2.0 version in PaperUI and reboot. Now new version is active and everything is working fine. Great  Job!!

If you can add meter_reset1 and meter_reset2 too will be great, because the meter_reset will reset only the consumption of switch 1, but the double switch has two electric meters.
