### ISSUE TITLE
Port COM3 does not exist (was WORKING BEFORE added openhabcloud)

### ISSUE THREAD

**Issue by eusblh** [openhab/org.openhab.binding.zwave#960]
I get error: "Port COM3 does not exist" from ZWaveSerialHandler, when I added openhabcloud+insteonplm1 to my zwave configuration. I know all other com port configurations and permissions are correct, because I can get zwave+insteonplm1 working and configured properly prior to adding openhabcloud. It also works with zwave+openhabcloud until I add insteonplm1. It just doesn't work with all 3. It initially works if I start with 2, and add the 3rd during runtime. But, it fails to connect to com port on restart. So, I think it's a timing issue during startup. This problem seems to be intermittent. But I got it to replicate by doing the following (I tried to find the simplest configuration that causes the error). 

I posted on community first. No response after 1 week. So, I'm posting here. 
https://community.openhab.org/t/port-com3-does-not-exist-was-working-before-added-openhabcloud/47702

Windows 10 
Processor: i3-4010U @ 1.70GHz
hardware: Zstick Gen 5 and Smarthome 2413U
* OH Version: 2.3 (and 2.4)
* Binding Version 2.3.0
Manual/Fresh install by extracting openhab-2.3.0.zip
(replicated on 2.4.0 SNAPSHOT as well)

edit addon.cfg (don't add insteonplm1 yet)
```   
ui = paper
binding =zwave
misc = openhabcloud
```
add insteonplm.cfg (to be used later)
```
javascript
port_0=COM1
```
[optional] reduce logging in org.ops4j.pax.logging.cfg
```   
log4j2.logger.smarthomeItemStateChangedEvent.name = smarthome.event.ItemStateChangedEvent
log4j2.logger.smarthomeItemStateChangedEvent.level = ERROR
log4j2.logger.iBinding.name = org.openhab.binding.insteonplm.InsteonPLMActiveBinding
log4j2.logger.iBinding.level = ERROR
```

start.bat
in paperui: Thing, add, zwave controller, Port=COM3, Add

While still running, edit addon.cfg to append insteonplm1:
```   
binding =zwave,insteonplm1
```

Note/confirm that COM1 and COM3 are open and functional 

logout
start.bat

you can ignore this first error if the openhabcloud is not properly configured. The COM3 error occurs whether openhabcloud is properly configured or not. 
[ERROR] [.io.openhabcloud.internal.CloudClient] - Socket.IO error: not authorized

Here's the problem: Serial Error: Port COM3 does not exist
```   
15:57:23.869 [INFO ] [ding.zwave.handler.ZWaveSerialHandler] - Connecting to serial port 'COM3'
15:57:23.874 [INFO ] [eonplm.internal.driver.SerialIOStream] - successfully opened port COM1
15:57:23.875 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:5eb338e6' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE): Controller is offline
15:57:23.897 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:5eb338e6' changed from OFFLINE (BRIDGE_OFFLINE): Controller is offline to OFFLINE (COMMUNICATION_ERROR): Serial Error: Port COM3 does not exist
```

Even if I put ZWaveSerialHandler in DEBUG, I do not get:
logger.debug("Starting receive thread");

If I remove openhabcloud and restart, error usually (but not always) goes away.

Let me know if you need help replicating or additional debug logs. 

While trying to make error occur, other configs I added/removed that seemed to make it worse, but not sure:
- rebooting the pc, error comes back on next start (even though it was not occurring on logout/start without reboot)
- binding =zwave,insteonplm1,cm11a,amazonechocontrol
- addons.cfg: misc=openhabcloud,market,restdocs
- Using a long expose string in openhabcloud.cfg:
```   
baseURL=https://myopenhab.org/
expose=foyer,toilet,powder,mbr2Porch,br3Porch,BackPorch,BackYardArt,bcloset,FrontDoor,FrontYard,jcloset,mbrPorchB,mbrPorchJ,Heat1,Speed3,bath,breakfast,dining,grill,hallway,kitchen,landscape,laundry,library,living,movie,night,pantry,party,pergola,pool,shade,stairs,dresser,lamps,basement,gArt,familyRm,heat,pump,Speed1,Speed2,Speed4,diningArt1,diningArt2,mirror,gAll,gInside,night,bar,master,bedroom
```

**Comment by cdjackson** [comment]
Sorry, but this issue list is to report bugs to developpers and I'm not really able to help with general support issues. You will have a MUCH larger audience on the forum - if no-one there can help, then posting here will also not help.

**Comment by eusblh** [comment]
I'm pretty sure this IS a code issue. I thought I wrote the post well enough to describe why this is not simple support, but a problem with the code. I'd be glad to troubleshoot this with you. I think it needs some additional debug statements added to determine. Please respond and let us continue this conversation. Can you describe why you think this is a support issue and not a code issue so I can reply?

**Comment by cdjackson** [comment]
All serial port communications is handled by another driver - not the binding. I don't see that this can be a bug with the code but if you can provide a debug log as requested in the issue template, I'll take a look.

**Comment by dude0001** [comment]
I am having the same problem@eusblh. It started after I updated the zwave binding to a snapshot build from earlier this year I found in the forums. I don't have access to produce a debug log right now (I've looked through them a bit myself) but I saw this pop up in my notifications thread and was curious as it sounded very familiar to my issue. I'm thinking about trying home-assistant for a while so not sure I'll get back to it, but wanted to let you know I think you are on the right track suspecting a defect some where.

**Comment by cdjackson** [comment]
Sorry, but as I've said I don't really see an issue with the binding here. If there is, you need to provide clear information. I see no link with openhabcloud and the ZWave binding so really I don't see why there is a problem with the cloud preventing the serial port working, then I don't think it's likely to be a problem with the binding. IT's much more likely that there is a hardware issue, or driver issue.

There are MANY reasons that serial ports might not work. If you have ZWAVE debug logs, then I will take a look, but we need to have clear information that shows a binding problem because right now I don't see this.

**Comment by eusblh** [comment]
>  I'm not really able to help with general support issues. You will have a MUCH larger audience on the forum

Was this the right place to post, or are you referring to somewhere else?:
https://community.openhab.org/t/port-com3-does-not-exist-was-working-before-added-openhabcloud/47702

> Sorry, but as I've said I don't really see an issue with the binding here. 

I agree it's probably not a problem in the zwave code, per se. That is just where I'm getting the error/symptom. I was hoping you'd know better how I can track down where the error is or who else can help me. Perhaps this could be fixed/worked-around by HOW/WHEN bindings are initialized. Where could I find someone that works on that level? 

> if you can provide a debug log as requested in the issue template, I'll take a look.

As I said in my original post, I did run DEBUG on ZWaveSerialHandler, it get's to this statement:
      logger.info("Connecting to serial port '{}'", portId);
but throws the exception (does not exist) before making it to this statement:
      logger.debug("Starting receive thread");
No other log output. 

Here's the relevant code snippet from ZWaveSerialHandler
```
 logger.info("Connecting to serial port '{}'", portId);
        try {
            CommPortIdentifier portIdentifier = CommPortIdentifier.getPortIdentifier(portId);
            CommPort commPort = portIdentifier.open("org.openhab.binding.zwave", 2000);
            serialPort = (SerialPort) commPort;
            serialPort.setSerialPortParams(115200, SerialPort.DATABITS_8, SerialPort.STOPBITS_1,
                    SerialPort.PARITY_NONE);
            serialPort.enableReceiveThreshold(1);
            serialPort.enableReceiveTimeout(SERIAL_RECEIVE_TIMEOUT);
            logger.debug("Starting receive thread");
  ...
        } catch (NoSuchPortException e) {
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.OFFLINE.COMMUNICATION_ERROR,
                    ZWaveBindingConstants.getI18nConstant(ZWaveBindingConstants.OFFLINE_SERIAL_EXISTS, portId));
...
```
Might it help to add some DEBUG statements to the ZWAVE code to at least determine which statement the problem is coming from? Could you help me with that? Would that help point to someone else that can help? Or some other place I can post that people will respond to? 

If it helps, I've run with DEBUG turned on for everything. And there's no further hint of a problem. (see partial logs below. I can provide the entire log, but that seemed pointless. Let me know if this is too little)

During the relevant timeframe, this is all I get out of openhab.log on full debug (I edited org.ops4j.pax.logging.cfg and changed all INFO/ERROR/WARN to DEBUG -- Am I turning on full DEBUG properly? Is there a way to get more debug or info out of the serial driver itself?)

```
2018-07-18 18:43:54.729 [INFO ] [ing.zwave.handler.ZWaveSerialHandler] - Connecting to serial port 'COM3'
2018-07-18 18:43:54.739 [DEBUG] [g.insteonplm.InsteonPLMActiveBinding] - got msg: IN:Cmd:0x57|RecordFlags:0xE2|ALLLinkGroup:0x01|LinkAddr:40.7B.8E|LinkData1:0x01|LinkData2:0x20|LinkData3:0x45|
2018-07-18 18:43:54.751 [DEBUG] [ding.insteonplm.internal.driver.Port] - writing (0): OUT:Cmd:0x6A|
2018-07-18 18:43:54.771 [DEBUG] [g.insteonplm.InsteonPLMActiveBinding] - got msg: IN:Cmd:0x57|RecordFlags:0xE2|ALLLinkGroup:0x01|LinkAddr:3D.1C.07|LinkData1:0x01|LinkData2:0x20|LinkData3:0x45|
2018-07-18 18:43:54.773 [DEBUG] [ding.insteonplm.internal.driver.Port] - writing (0): OUT:Cmd:0x6A|
... 
```
nothing else from ZWaveSerialHandler, or anything else related to serial ports. I didn't provide any more of the log, because by 18:43:54.753, the error has already occurred (see event log below)
this is what i get from Event.log (it helps to note timestamps between the two logs)
```
2018-07-18 18:43:54.695 [event.ThingStatusInfoEvent] - 'zwave:serial_zstick:5eb338e6' updated: INITIALIZING
2018-07-18 18:43:54.710 [hingStatusInfoChangedEvent] - 'zwave:serial_zstick:5eb338e6' changed from UNINITIALIZED to INITIALIZING
2018-07-18 18:43:54.729 [event.ThingStatusInfoEvent] - 'zwave:serial_zstick:5eb338e6' updated: OFFLINE (BRIDGE_OFFLINE): Controller is offline
2018-07-18 18:43:54.750 [hingStatusInfoChangedEvent] - 'zwave:serial_zstick:5eb338e6' changed from INITIALIZING to OFFLINE (BRIDGE_OFFLINE): Controller is offline
2018-07-18 18:43:54.751 [event.ThingStatusInfoEvent] - 'zwave:serial_zstick:5eb338e6' updated: OFFLINE (COMMUNICATION_ERROR): Serial Error: Port COM3 does not exist
2018-07-18 18:43:54.753 [hingStatusInfoChangedEvent] - 'zwave:serial_zstick:5eb338e6' changed from OFFLINE (BRIDGE_OFFLINE): Controller is offline to OFFLINE (COMMUNICATION_ERROR): Serial Error: Port COM3 does not exist

```

**Comment by cdjackson** [comment]
> it get's to this statement:
logger.info("Connecting to serial port '{}'", portId);
but throws the exception (does not exist) before making it to this statement:

Then this is an issue with the driver, or maybe an issue with permissions in your system. It's not an issue with the ZWave binding, and I don't see how it can be related to openhabcloud which is also not related to the ZWave binding.

Sorry - but I'm not familiar with the low level serial driver, or Windows serial ports so I can't really help. By far the best place is the community forum - normally there's someone who will help there - there are tens of thousands of users there, and a very small number of people on this list here.

**Comment by eusblh** [comment]
one new piece of info: I installed your development version of the zwave binding. And the problem went away. 
2.4.0.201807161952     | ZWave Binding

**Comment by cdjackson** [comment]
There is no difference in COM port access in the development version or the master version.
