### ISSUE TITLE
Implement reconnect if device is not ready or disconnected

### ISSUE THREAD

**Issue by dottedmag** [openhab/org.openhab.binding.zwave#979]
It would be nice if Z-Wave binding was reconnecting to a device if it is not ready on startup or was disconnected and later reconnected (like Aeotec USB dongle).

I have an implementation and will submit a PR soon.

**Comment by cdjackson** [comment]
Please ensure any PRs are against the development branch only as it will not be possible to merge master.

**Comment by cdjackson** [comment]
Closing as duplicate of #1213
